# Use AWS Lambda Go base image
FROM public.ecr.aws/lambda/go:1

# Install necessary dependencies including xz
RUN yum install -y zip go

# Set the working directory to /app
WORKDIR /app

# Copy all contents from the current directory to the container
COPY . .

# Build the Go application with Zig as the C/CXX compiler
RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o bootstrap && zip lambda-handler.zip bootstrap